# The name of the workflow
name: Build and Test

# This workflow will run on any push to the repository
on: push

jobs:
  test:
    # Set up a virtual machine to run the tests
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Check out the code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run tests with Vitest
      - name: Test with Vitest
        run: |
          npm run test
